[project]
name = "vi-slam"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=24.10.0",
    "matplotlib>=3.9.3",
    "numpy>=2.2.0",
    "opencv-python>=4.10.0.84",
    "tqdm>=4.67.1",
]
